package com.codename1.k9tests;

import com.codename1.ui.Container;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.util.Resources;


public class MessageComposeRecipients extends Container  {
    public MessageComposeRecipients(com.codename1.ui.util.Resources resourceObjectInstance) {
        initGuiBuilderComponents(resourceObjectInstance);
    }

//-- DON'T EDIT BELOW THIS LINE!!!
    private com.codename1.ui.Container gui_ = new com.codename1.ui.Container(new com.codename1.ui.layouts.BoxLayout(com.codename1.ui.layouts.BoxLayout.X_AXIS));
    private com.codename1.components.SpanLabel gui_fromlabel = new com.codename1.components.SpanLabel();
    private com.codename1.ui.Label gui_identity = new com.codename1.ui.Label();
    private com.codename1.ui.Label gui_pgpinlineindicator = new com.codename1.ui.Label();
    private com.codename1.ui.Container gui_cryptostatus = new com.codename1.ui.Container(new com.codename1.ui.layouts.FlowLayout());
    private com.codename1.ui.Label gui__1 = new com.codename1.ui.Label();
    private com.codename1.ui.Label gui__2 = new com.codename1.ui.Label();
    private com.codename1.ui.Container gui__3 = new com.codename1.ui.Container(new com.codename1.ui.layouts.BorderLayout());
    private com.codename1.ui.Container gui_null = new com.codename1.ui.Container(new com.codename1.ui.layouts.BoxLayout(com.codename1.ui.layouts.BoxLayout.X_AXIS));
    private com.codename1.ui.Label gui__4 = new com.codename1.ui.Label();
    private com.codename1.ui.Label gui__5 = new com.codename1.ui.Label();
    private com.codename1.ui.Container gui__6 = new com.codename1.ui.Container(new com.codename1.ui.layouts.BorderLayout());
    private com.codename1.ui.Container gui_null_1 = new com.codename1.ui.Container(new com.codename1.ui.layouts.BoxLayout(com.codename1.ui.layouts.BoxLayout.X_AXIS));
    private com.codename1.ui.Label gui__7 = new com.codename1.ui.Label();
    private com.codename1.ui.Label gui__8 = new com.codename1.ui.Label();
    private com.codename1.ui.Container gui__9 = new com.codename1.ui.Container(new com.codename1.ui.layouts.BorderLayout());
    private com.codename1.ui.Container gui_null_2 = new com.codename1.ui.Container(new com.codename1.ui.layouts.BoxLayout(com.codename1.ui.layouts.BoxLayout.X_AXIS));
    private com.codename1.ui.Label gui__10 = new com.codename1.ui.Label();
    private com.codename1.ui.Label gui__11 = new com.codename1.ui.Label();
    private com.codename1.ui.Label gui__12 = new com.codename1.ui.Label();
    private com.codename1.ui.Container gui__13 = new com.codename1.ui.Container(new com.codename1.ui.layouts.BorderLayout());
    private com.codename1.ui.Container gui_null_3 = new com.codename1.ui.Container(new com.codename1.ui.layouts.BoxLayout(com.codename1.ui.layouts.BoxLayout.X_AXIS));
    private com.codename1.ui.Label gui__14 = new com.codename1.ui.Label();
    private com.codename1.ui.Label gui__15 = new com.codename1.ui.Label();
    private com.codename1.ui.Container gui__16 = new com.codename1.ui.Container(new com.codename1.ui.layouts.BorderLayout());
    private com.codename1.ui.Container gui_null_4 = new com.codename1.ui.Container(new com.codename1.ui.layouts.BoxLayout(com.codename1.ui.layouts.BoxLayout.X_AXIS));
    private com.codename1.ui.Label gui__17 = new com.codename1.ui.Label();
    private com.codename1.ui.Label gui__18 = new com.codename1.ui.Label();
    private com.codename1.ui.Label gui__19 = new com.codename1.ui.Label();
    private com.codename1.ui.Container gui__20 = new com.codename1.ui.Container(new com.codename1.ui.layouts.FlowLayout());
    private com.codename1.ui.Container gui_towrapper = new com.codename1.ui.Container(new com.codename1.ui.layouts.BoxLayout(com.codename1.ui.layouts.BoxLayout.Y_AXIS));
    private com.codename1.components.SpanLabel gui_tolabel = new com.codename1.components.SpanLabel();
    private com.codename1.ui.Container gui_to = new com.codename1.ui.Container(new com.codename1.ui.layouts.FlowLayout());
    private com.codename1.ui.Container gui_recipientexpandercontainer = new com.codename1.ui.Container(new com.codename1.ui.layouts.BorderLayout());
    private com.codename1.ui.Container gui_null_5 = new com.codename1.ui.Container(new com.codename1.ui.layouts.BoxLayout(com.codename1.ui.layouts.BoxLayout.X_AXIS));
    private com.codename1.ui.Label gui_recipientexpander = new com.codename1.ui.Label();
    private com.codename1.ui.Container gui__21 = new com.codename1.ui.Container(new com.codename1.ui.layouts.FlowLayout());
    private com.codename1.ui.Container gui__22 = new com.codename1.ui.Container(new com.codename1.ui.layouts.FlowLayout());
    private com.codename1.ui.Container gui_ccwrapper = new com.codename1.ui.Container(new com.codename1.ui.layouts.BoxLayout(com.codename1.ui.layouts.BoxLayout.X_AXIS));
    private com.codename1.components.SpanLabel gui_cclabel = new com.codename1.components.SpanLabel();
    private com.codename1.ui.Container gui_cc = new com.codename1.ui.Container(new com.codename1.ui.layouts.FlowLayout());
    private com.codename1.ui.Container gui_ccdivider = new com.codename1.ui.Container(new com.codename1.ui.layouts.FlowLayout());
    private com.codename1.ui.Container gui_bccwrapper = new com.codename1.ui.Container(new com.codename1.ui.layouts.BoxLayout(com.codename1.ui.layouts.BoxLayout.X_AXIS));
    private com.codename1.components.SpanLabel gui_bcclabel = new com.codename1.components.SpanLabel();
    private com.codename1.ui.Container gui_bcc = new com.codename1.ui.Container(new com.codename1.ui.layouts.FlowLayout());
    private com.codename1.ui.Container gui_bccdivider = new com.codename1.ui.Container(new com.codename1.ui.layouts.FlowLayout());


// <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initGuiBuilderComponents(com.codename1.ui.util.Resources resourceObjectInstance) {
        setLayout(new com.codename1.ui.layouts.BoxLayout(com.codename1.ui.layouts.BoxLayout.Y_AXIS));
        setName("MessageComposeRecipients");
        addComponent(gui_);
        gui_.setName("");
        gui_.addComponent(gui_fromlabel);
        gui_.addComponent(gui_identity);
        gui_.addComponent(gui_pgpinlineindicator);
        gui_.addComponent(gui_cryptostatus);
        gui_cryptostatus.setName("cryptostatus");
        gui_cryptostatus.addComponent(gui__1);
        gui_cryptostatus.addComponent(gui__2);
        gui_cryptostatus.addComponent(gui__3);
        gui__3.setName("_3");
        gui__3.addComponent(com.codename1.ui.layouts.BorderLayout.CENTER, gui_null);
        gui_null.addComponent(gui__4);
        gui_null.addComponent(gui__5);
        gui__4.setName("_4");
        gui__5.setName("_5");
        gui_cryptostatus.addComponent(gui__6);
        gui__6.setName("_6");
        gui__6.addComponent(com.codename1.ui.layouts.BorderLayout.CENTER, gui_null_1);
        gui_null_1.setName("null_1");
        gui_null_1.addComponent(gui__7);
        gui_null_1.addComponent(gui__8);
        gui__7.setName("_7");
        gui__8.setName("_8");
        gui_null_1.setName("null_1");
        gui_cryptostatus.addComponent(gui__9);
        gui__9.setName("_9");
        gui__9.addComponent(com.codename1.ui.layouts.BorderLayout.CENTER, gui_null_2);
        gui_null_2.setName("null_2");
        gui_null_2.addComponent(gui__10);
        gui_null_2.addComponent(gui__11);
        gui_null_2.addComponent(gui__12);
        gui__10.setName("_10");
        gui__11.setName("_11");
        gui__12.setName("_12");
        gui_null_2.setName("null_2");
        gui_cryptostatus.addComponent(gui__13);
        gui__13.setName("_13");
        gui__13.addComponent(com.codename1.ui.layouts.BorderLayout.CENTER, gui_null_3);
        gui_null_3.setName("null_3");
        gui_null_3.addComponent(gui__14);
        gui_null_3.addComponent(gui__15);
        gui__14.setName("_14");
        gui__15.setName("_15");
        gui_null_3.setName("null_3");
        gui_cryptostatus.addComponent(gui__16);
        gui__16.setName("_16");
        gui__16.addComponent(com.codename1.ui.layouts.BorderLayout.CENTER, gui_null_4);
        gui_null_4.setName("null_4");
        gui_null_4.addComponent(gui__17);
        gui_null_4.addComponent(gui__18);
        gui__17.setName("_17");
        gui__18.setName("_18");
        gui_null_4.setName("null_4");
        gui_cryptostatus.addComponent(gui__19);
        gui__1.setName("_1");
        gui__2.setName("_2");
        gui__3.setName("_3");
        gui__6.setName("_6");
        gui__9.setName("_9");
        gui__13.setName("_13");
        gui__16.setName("_16");
        gui__19.setName("_19");
        gui_fromlabel.setText("recipient_from");
        gui_fromlabel.setName("fromlabel");
        gui_identity.setText("");
        gui_identity.setName("identity");
        gui_pgpinlineindicator.setName("pgpinlineindicator");
        gui_cryptostatus.setName("cryptostatus");
        addComponent(gui__20);
        addComponent(gui_towrapper);
        gui_towrapper.setName("towrapper");
        gui_towrapper.addComponent(gui_tolabel);
        gui_towrapper.addComponent(gui_to);
        gui_towrapper.addComponent(gui_recipientexpandercontainer);
        gui_recipientexpandercontainer.setName("recipientexpandercontainer");
        gui_recipientexpandercontainer.addComponent(com.codename1.ui.layouts.BorderLayout.CENTER, gui_null_5);
        gui_null_5.setName("null_5");
        gui_null_5.addComponent(gui_recipientexpander);
        gui_null_5.addComponent(gui__21);
        gui_recipientexpander.setName("recipientexpander");
        gui__21.setName("_21");
        gui_null_5.setName("null_5");
        gui_tolabel.setText("recipient_to");
        gui_tolabel.setName("tolabel");
        gui_to.setName("to");
        gui_recipientexpandercontainer.setName("recipientexpandercontainer");
        addComponent(gui__22);
        addComponent(gui_ccwrapper);
        gui_ccwrapper.setName("ccwrapper");
        gui_ccwrapper.addComponent(gui_cclabel);
        gui_ccwrapper.addComponent(gui_cc);
        gui_cclabel.setText("recipient_cc");
        gui_cclabel.setName("cclabel");
        gui_cc.setName("cc");
        addComponent(gui_ccdivider);
        addComponent(gui_bccwrapper);
        gui_bccwrapper.setName("bccwrapper");
        gui_bccwrapper.addComponent(gui_bcclabel);
        gui_bccwrapper.addComponent(gui_bcc);
        gui_bcclabel.setText("recipient_bcc");
        gui_bcclabel.setName("bcclabel");
        gui_bcc.setName("bcc");
        addComponent(gui_bccdivider);
        gui_.setName("");
        gui__20.setName("_20");
        gui_towrapper.setName("towrapper");
        gui__22.setName("_22");
        gui_ccwrapper.setName("ccwrapper");
        gui_ccdivider.setName("ccdivider");
        gui_bccwrapper.setName("bccwrapper");
        gui_bccdivider.setName("bccdivider");
    }// </editor-fold>

//-- DON'T EDIT ABOVE THIS LINE!!!
}
