package ca.weblite.testui;

import com.codename1.ui.Container;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.util.Resources;


public class AccountSetupIncoming extends Container  {
    public AccountSetupIncoming(com.codename1.ui.util.Resources resourceObjectInstance) {
        initGuiBuilderComponents(resourceObjectInstance);
    }

//-- DON'T EDIT BELOW THIS LINE!!!
    private com.codename1.ui.Container gui_ = new com.codename1.ui.Container(new com.codename1.ui.layouts.BoxLayout(com.codename1.ui.layouts.BoxLayout.Y_AXIS));
    private com.codename1.ui.Container gui__1 = new com.codename1.ui.Container(new com.codename1.ui.layouts.BoxLayout(com.codename1.ui.layouts.BoxLayout.Y_AXIS));
    private com.codename1.components.SpanLabel gui_accountserverlabel = new com.codename1.components.SpanLabel();
    private com.codename1.ui.Label gui_accountserver = new com.codename1.ui.Label();
    private com.codename1.components.SpanLabel gui__2 = new com.codename1.components.SpanLabel();
    private com.codename1.ui.spinner.GenericSpinner gui_accountsecuritytype = new com.codename1.ui.spinner.GenericSpinner();
    private com.codename1.components.SpanLabel gui__3 = new com.codename1.components.SpanLabel();
    private com.codename1.ui.Label gui_accountport = new com.codename1.ui.Label();
    private com.codename1.components.SpanLabel gui__4 = new com.codename1.components.SpanLabel();
    private com.codename1.ui.Label gui_accountusername = new com.codename1.ui.Label();
    private com.codename1.components.SpanLabel gui_accountauthtypelabel = new com.codename1.components.SpanLabel();
    private com.codename1.ui.spinner.GenericSpinner gui_accountauthtype = new com.codename1.ui.spinner.GenericSpinner();
    private com.codename1.components.SpanLabel gui_accountpasswordlabel = new com.codename1.components.SpanLabel();
    private com.codename1.ui.Label gui_accountpassword = new com.codename1.ui.Label();
    private com.codename1.components.SpanLabel gui_accountclientcertificatelabel = new com.codename1.components.SpanLabel();
    private com.codename1.ui.Container gui_accountclientcertificatespinner = new com.codename1.ui.Container(new com.codename1.ui.layouts.FlowLayout());
    private com.codename1.ui.Container gui_imappathprefixsection = new com.codename1.ui.Container(new com.codename1.ui.layouts.BoxLayout(com.codename1.ui.layouts.BoxLayout.Y_AXIS));
    private com.codename1.ui.CheckBox gui_imapautodetectnamespace = new com.codename1.ui.CheckBox();
    private com.codename1.components.SpanLabel gui__5 = new com.codename1.components.SpanLabel();
    private com.codename1.ui.Label gui_imappathprefix = new com.codename1.ui.Label();
    private com.codename1.ui.Container gui_imapfoldersetupsection = new com.codename1.ui.Container(new com.codename1.ui.layouts.BoxLayout(com.codename1.ui.layouts.BoxLayout.Y_AXIS));
    private com.codename1.ui.CheckBox gui_subscribedfoldersonly = new com.codename1.ui.CheckBox();
    private com.codename1.ui.Container gui_webdavadvancedheader = new com.codename1.ui.Container(new com.codename1.ui.layouts.BoxLayout(com.codename1.ui.layouts.BoxLayout.Y_AXIS));
    private com.codename1.ui.Label gui__6 = new com.codename1.ui.Label();
    private com.codename1.ui.Container gui_webdavmailboxaliassection = new com.codename1.ui.Container(new com.codename1.ui.layouts.BoxLayout(com.codename1.ui.layouts.BoxLayout.Y_AXIS));
    private com.codename1.components.SpanLabel gui__7 = new com.codename1.components.SpanLabel();
    private com.codename1.ui.Label gui_webdavmailboxpath = new com.codename1.ui.Label();
    private com.codename1.ui.Container gui_webdavowapathsection = new com.codename1.ui.Container(new com.codename1.ui.layouts.BoxLayout(com.codename1.ui.layouts.BoxLayout.Y_AXIS));
    private com.codename1.components.SpanLabel gui__8 = new com.codename1.components.SpanLabel();
    private com.codename1.ui.Label gui_webdavpathprefix = new com.codename1.ui.Label();
    private com.codename1.ui.Container gui_webdavauthpathsection = new com.codename1.ui.Container(new com.codename1.ui.layouts.BoxLayout(com.codename1.ui.layouts.BoxLayout.Y_AXIS));
    private com.codename1.components.SpanLabel gui__9 = new com.codename1.components.SpanLabel();
    private com.codename1.ui.Label gui_webdavauthpath = new com.codename1.ui.Label();
    private com.codename1.components.SpanLabel gui_compressionlabel = new com.codename1.components.SpanLabel();
    private com.codename1.ui.Container gui_compressionsection = new com.codename1.ui.Container(new com.codename1.ui.layouts.BoxLayout(com.codename1.ui.layouts.BoxLayout.X_AXIS));
    private com.codename1.ui.CheckBox gui_compressionmobile = new com.codename1.ui.CheckBox();
    private com.codename1.ui.CheckBox gui_compressionwifi = new com.codename1.ui.CheckBox();
    private com.codename1.ui.CheckBox gui_compressionother = new com.codename1.ui.CheckBox();
    private com.codename1.ui.Container gui__10 = new com.codename1.ui.Container(new com.codename1.ui.layouts.FlowLayout());
    private com.codename1.ui.Container gui__11 = new com.codename1.ui.Container(new com.codename1.ui.layouts.FlowLayout());
    private com.codename1.ui.Container gui_divider = new com.codename1.ui.Container(new com.codename1.ui.layouts.FlowLayout());
    private com.codename1.ui.Container gui__12 = new com.codename1.ui.Container(new com.codename1.ui.layouts.BoxLayout(com.codename1.ui.layouts.BoxLayout.X_AXIS));
    private com.codename1.ui.Container gui__13 = new com.codename1.ui.Container(new com.codename1.ui.layouts.FlowLayout());
    private com.codename1.ui.Button gui_next = new com.codename1.ui.Button();


// <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initGuiBuilderComponents(com.codename1.ui.util.Resources resourceObjectInstance) {
        setLayout(new com.codename1.ui.layouts.BoxLayout(com.codename1.ui.layouts.BoxLayout.Y_AXIS));
        setUIID("Container3Android");
        setName("AccountSetupIncoming");
        addComponent(gui_);
        gui_.setScrollableY(true);
        gui_.setUIID("Container3Android");
        gui_.setName("");
        gui_.addComponent(gui__1);
        gui__1.setUIID("Container3Android");
        gui__1.setName("_1");
        gui__1.addComponent(gui_accountserverlabel);
        gui__1.addComponent(gui_accountserver);
        gui__1.addComponent(gui__2);
        gui__1.addComponent(gui_accountsecuritytype);
        gui__1.addComponent(gui__3);
        gui__1.addComponent(gui_accountport);
        gui__1.addComponent(gui__4);
        gui__1.addComponent(gui_accountusername);
        gui__1.addComponent(gui_accountauthtypelabel);
        gui__1.addComponent(gui_accountauthtype);
        gui__1.addComponent(gui_accountpasswordlabel);
        gui__1.addComponent(gui_accountpassword);
        gui__1.addComponent(gui_accountclientcertificatelabel);
        gui__1.addComponent(gui_accountclientcertificatespinner);
        gui__1.addComponent(gui_imappathprefixsection);
        gui_imappathprefixsection.setUIID("Container3Android");
        gui_imappathprefixsection.setName("imappathprefixsection");
        gui_imappathprefixsection.addComponent(gui_imapautodetectnamespace);
        gui_imappathprefixsection.addComponent(gui__5);
        gui_imappathprefixsection.addComponent(gui_imappathprefix);
        gui_imapautodetectnamespace.setText("account_setup_incoming_autodetect_namespace_label");
        gui_imapautodetectnamespace.setUIID("CheckBox12Android");
        gui_imapautodetectnamespace.setName("imapautodetectnamespace");
        gui__5.setText("account_setup_incoming_imap_path_prefix_label");
        gui__5.setUIID("SpanLabel37Android");
        gui__5.setName("_5");
        gui_imappathprefix.setUIID("Label10Android");
        gui_imappathprefix.setName("imappathprefix");
        gui__1.addComponent(gui_imapfoldersetupsection);
        gui_imapfoldersetupsection.setUIID("Container3Android");
        gui_imapfoldersetupsection.setName("imapfoldersetupsection");
        gui_imapfoldersetupsection.addComponent(gui_subscribedfoldersonly);
        gui_subscribedfoldersonly.setText("account_setup_incoming_subscribed_folders_only_label");
        gui_subscribedfoldersonly.setUIID("CheckBox12Android");
        gui_subscribedfoldersonly.setName("subscribedfoldersonly");
        gui__1.addComponent(gui_webdavadvancedheader);
        gui_webdavadvancedheader.setUIID("Container3Android");
        gui_webdavadvancedheader.setName("webdavadvancedheader");
        gui_webdavadvancedheader.addComponent(gui__6);
        gui__6.setText("advanced");
        gui__6.setUIID("Label10Android");
        gui__6.setName("_6");
        gui__1.addComponent(gui_webdavmailboxaliassection);
        gui_webdavmailboxaliassection.setUIID("Container3Android");
        gui_webdavmailboxaliassection.setName("webdavmailboxaliassection");
        gui_webdavmailboxaliassection.addComponent(gui__7);
        gui_webdavmailboxaliassection.addComponent(gui_webdavmailboxpath);
        gui__7.setText("account_setup_incoming_webdav_mailbox_path_label");
        gui__7.setUIID("SpanLabel37Android");
        gui__7.setName("_7");
        gui_webdavmailboxpath.setUIID("Label10Android");
        gui_webdavmailboxpath.setName("webdavmailboxpath");
        gui__1.addComponent(gui_webdavowapathsection);
        gui_webdavowapathsection.setUIID("Container3Android");
        gui_webdavowapathsection.setName("webdavowapathsection");
        gui_webdavowapathsection.addComponent(gui__8);
        gui_webdavowapathsection.addComponent(gui_webdavpathprefix);
        gui__8.setText("account_setup_incoming_webdav_path_prefix_label");
        gui__8.setUIID("SpanLabel37Android");
        gui__8.setName("_8");
        gui_webdavpathprefix.setUIID("Label10Android");
        gui_webdavpathprefix.setName("webdavpathprefix");
        gui__1.addComponent(gui_webdavauthpathsection);
        gui_webdavauthpathsection.setUIID("Container3Android");
        gui_webdavauthpathsection.setName("webdavauthpathsection");
        gui_webdavauthpathsection.addComponent(gui__9);
        gui_webdavauthpathsection.addComponent(gui_webdavauthpath);
        gui__9.setText("account_setup_incoming_webdav_auth_path_label");
        gui__9.setUIID("SpanLabel37Android");
        gui__9.setName("_9");
        gui_webdavauthpath.setUIID("Label10Android");
        gui_webdavauthpath.setName("webdavauthpath");
        gui__1.addComponent(gui_compressionlabel);
        gui__1.addComponent(gui_compressionsection);
        gui_compressionsection.setUIID("Container3Android");
        gui_compressionsection.setName("compressionsection");
        gui_compressionsection.addComponent(gui_compressionmobile);
        gui_compressionsection.addComponent(gui_compressionwifi);
        gui_compressionsection.addComponent(gui_compressionother);
        gui_compressionmobile.setText("account_setup_incoming_mobile_label");
        gui_compressionmobile.setUIID("CheckBox12Android");
        gui_compressionmobile.setName("compressionmobile");
        gui_compressionwifi.setText("account_setup_incoming_wifi_label");
        gui_compressionwifi.setUIID("CheckBox12Android");
        gui_compressionwifi.setName("compressionwifi");
        gui_compressionother.setText("account_setup_incoming_other_label");
        gui_compressionother.setUIID("CheckBox12Android");
        gui_compressionother.setName("compressionother");
        gui__1.addComponent(gui__10);
        gui_accountserverlabel.setText("account_setup_incoming_pop_server_label");
        gui_accountserverlabel.setUIID("SpanLabel37Android");
        gui_accountserverlabel.setName("accountserverlabel");
        gui_accountserver.setUIID("Label10Android");
        gui_accountserver.setName("accountserver");
        gui__2.setText("account_setup_incoming_security_label");
        gui__2.setUIID("SpanLabel37Android");
        gui__2.setName("_2");
        gui_accountsecuritytype.setUIID("GenericSpinner56Android");
        gui_accountsecuritytype.setName("accountsecuritytype");
        gui__3.setText("account_setup_incoming_port_label");
        gui__3.setUIID("SpanLabel37Android");
        gui__3.setName("_3");
        gui_accountport.setUIID("Label10Android");
        gui_accountport.setName("accountport");
        gui__4.setText("account_setup_incoming_username_label");
        gui__4.setUIID("SpanLabel37Android");
        gui__4.setName("_4");
        gui_accountusername.setUIID("Label10Android");
        gui_accountusername.setName("accountusername");
        gui_accountauthtypelabel.setText("account_setup_incoming_auth_type_label");
        gui_accountauthtypelabel.setUIID("SpanLabel37Android");
        gui_accountauthtypelabel.setName("accountauthtypelabel");
        gui_accountauthtype.setUIID("GenericSpinner56Android");
        gui_accountauthtype.setName("accountauthtype");
        gui_accountpasswordlabel.setText("account_setup_incoming_password_label");
        gui_accountpasswordlabel.setUIID("SpanLabel37Android");
        gui_accountpasswordlabel.setName("accountpasswordlabel");
        gui_accountpassword.setUIID("Label10Android");
        gui_accountpassword.setName("accountpassword");
        gui_accountclientcertificatelabel.setText("account_setup_incoming_client_certificate_label");
        gui_accountclientcertificatelabel.setUIID("SpanLabel37Android");
        gui_accountclientcertificatelabel.setName("accountclientcertificatelabel");
        gui_accountclientcertificatespinner.setUIID("Container3Android");
        gui_accountclientcertificatespinner.setName("accountclientcertificatespinner");
        gui_imappathprefixsection.setUIID("Container3Android");
        gui_imappathprefixsection.setName("imappathprefixsection");
        gui_imapfoldersetupsection.setUIID("Container3Android");
        gui_imapfoldersetupsection.setName("imapfoldersetupsection");
        gui_webdavadvancedheader.setUIID("Container3Android");
        gui_webdavadvancedheader.setName("webdavadvancedheader");
        gui_webdavmailboxaliassection.setUIID("Container3Android");
        gui_webdavmailboxaliassection.setName("webdavmailboxaliassection");
        gui_webdavowapathsection.setUIID("Container3Android");
        gui_webdavowapathsection.setName("webdavowapathsection");
        gui_webdavauthpathsection.setUIID("Container3Android");
        gui_webdavauthpathsection.setName("webdavauthpathsection");
        gui_compressionlabel.setText("account_setup_incoming_compression_label");
        gui_compressionlabel.setUIID("SpanLabel37Android");
        gui_compressionlabel.setName("compressionlabel");
        gui_compressionsection.setUIID("Container3Android");
        gui_compressionsection.setName("compressionsection");
        gui__10.setUIID("Container3Android");
        gui__10.setName("_10");
        gui__1.setUIID("Container3Android");
        gui__1.setName("_1");
        addComponent(gui__11);
        gui__11.setUIID("Container3Android");
        gui__11.setName("_11");
        gui__11.addComponent(gui_divider);
        gui__11.addComponent(gui__12);
        gui__12.setUIID("Container3Android");
        gui__12.setName("_12");
        gui__12.addComponent(gui__13);
        gui__12.addComponent(gui_next);
        gui__13.setUIID("Container3Android");
        gui__13.setName("_13");
        gui_next.setText("next_action");
        gui_next.setUIID("Button20Android");
        gui_next.setName("next");
        gui_divider.setUIID("Container3Android");
        gui_divider.setName("divider");
        gui__12.setUIID("Container3Android");
        gui__12.setName("_12");
        gui_.setScrollableY(true);
        gui_.setUIID("Container3Android");
        gui_.setName("");
        gui__11.setUIID("Container3Android");
        gui__11.setName("_11");
    }// </editor-fold>

//-- DON'T EDIT ABOVE THIS LINE!!!
}
