package ca.weblite.testui;

import com.codename1.ui.Container;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.util.Resources;


public class MessageCompose extends Container  {
    public MessageCompose(com.codename1.ui.util.Resources resourceObjectInstance) {
        initGuiBuilderComponents(resourceObjectInstance);
    }

//-- DON'T EDIT BELOW THIS LINE!!!
    private com.codename1.ui.Container gui_ = new com.codename1.ui.Container(new com.codename1.ui.layouts.BoxLayout(com.codename1.ui.layouts.BoxLayout.Y_AXIS));
    private com.codename1.ui.Container gui__1 = new com.codename1.ui.Container(new com.codename1.ui.layouts.BoxLayout(com.codename1.ui.layouts.BoxLayout.Y_AXIS));
    private com.codename1.ui.Container gui__2 = new com.codename1.ui.Container(new com.codename1.ui.layouts.BoxLayout(com.codename1.ui.layouts.BoxLayout.Y_AXIS));
    private com.codename1.ui.Container gui__3 = new com.codename1.ui.Container(new com.codename1.ui.layouts.BoxLayout(com.codename1.ui.layouts.BoxLayout.X_AXIS));
    private com.codename1.ui.Label gui_fromlabel = new com.codename1.ui.Label();
    private com.codename1.ui.Label gui_identity = new com.codename1.ui.Label();
    private com.codename1.ui.Label gui_pgpinlineindicator = new com.codename1.ui.Label();
    private com.codename1.ui.Container gui_cryptostatus = new com.codename1.ui.Container(new com.codename1.ui.layouts.FlowLayout());
    private com.codename1.ui.Label gui__4 = new com.codename1.ui.Label();
    private com.codename1.ui.Label gui__5 = new com.codename1.ui.Label();
    private com.codename1.ui.Container gui__6 = new com.codename1.ui.Container(new com.codename1.ui.layouts.BorderLayout());
    private com.codename1.ui.Container gui_null = new com.codename1.ui.Container(new com.codename1.ui.layouts.BoxLayout(com.codename1.ui.layouts.BoxLayout.X_AXIS));
    private com.codename1.ui.Label gui__7 = new com.codename1.ui.Label();
    private com.codename1.ui.Label gui__8 = new com.codename1.ui.Label();
    private com.codename1.ui.Container gui__9 = new com.codename1.ui.Container(new com.codename1.ui.layouts.BorderLayout());
    private com.codename1.ui.Container gui_null_1 = new com.codename1.ui.Container(new com.codename1.ui.layouts.BoxLayout(com.codename1.ui.layouts.BoxLayout.X_AXIS));
    private com.codename1.ui.Label gui__10 = new com.codename1.ui.Label();
    private com.codename1.ui.Label gui__11 = new com.codename1.ui.Label();
    private com.codename1.ui.Container gui__12 = new com.codename1.ui.Container(new com.codename1.ui.layouts.BorderLayout());
    private com.codename1.ui.Container gui_null_2 = new com.codename1.ui.Container(new com.codename1.ui.layouts.BoxLayout(com.codename1.ui.layouts.BoxLayout.X_AXIS));
    private com.codename1.ui.Label gui__13 = new com.codename1.ui.Label();
    private com.codename1.ui.Label gui__14 = new com.codename1.ui.Label();
    private com.codename1.ui.Label gui__15 = new com.codename1.ui.Label();
    private com.codename1.ui.Container gui__16 = new com.codename1.ui.Container(new com.codename1.ui.layouts.BorderLayout());
    private com.codename1.ui.Container gui_null_3 = new com.codename1.ui.Container(new com.codename1.ui.layouts.BoxLayout(com.codename1.ui.layouts.BoxLayout.X_AXIS));
    private com.codename1.ui.Label gui__17 = new com.codename1.ui.Label();
    private com.codename1.ui.Label gui__18 = new com.codename1.ui.Label();
    private com.codename1.ui.Container gui__19 = new com.codename1.ui.Container(new com.codename1.ui.layouts.BorderLayout());
    private com.codename1.ui.Container gui_null_4 = new com.codename1.ui.Container(new com.codename1.ui.layouts.BoxLayout(com.codename1.ui.layouts.BoxLayout.X_AXIS));
    private com.codename1.ui.Label gui__20 = new com.codename1.ui.Label();
    private com.codename1.ui.Label gui__21 = new com.codename1.ui.Label();
    private com.codename1.ui.Label gui__22 = new com.codename1.ui.Label();
    private com.codename1.ui.Container gui__23 = new com.codename1.ui.Container(new com.codename1.ui.layouts.FlowLayout());
    private com.codename1.ui.Container gui_towrapper = new com.codename1.ui.Container(new com.codename1.ui.layouts.BoxLayout(com.codename1.ui.layouts.BoxLayout.Y_AXIS));
    private com.codename1.ui.Label gui_tolabel = new com.codename1.ui.Label();
    private com.codename1.ui.Container gui_to = new com.codename1.ui.Container(new com.codename1.ui.layouts.FlowLayout());
    private com.codename1.ui.Container gui_recipientexpandercontainer = new com.codename1.ui.Container(new com.codename1.ui.layouts.BorderLayout());
    private com.codename1.ui.Container gui_null_5 = new com.codename1.ui.Container(new com.codename1.ui.layouts.BoxLayout(com.codename1.ui.layouts.BoxLayout.X_AXIS));
    private com.codename1.ui.Label gui_recipientexpander = new com.codename1.ui.Label();
    private com.codename1.ui.Container gui__24 = new com.codename1.ui.Container(new com.codename1.ui.layouts.FlowLayout());
    private com.codename1.ui.Container gui__25 = new com.codename1.ui.Container(new com.codename1.ui.layouts.FlowLayout());
    private com.codename1.ui.Container gui_ccwrapper = new com.codename1.ui.Container(new com.codename1.ui.layouts.BoxLayout(com.codename1.ui.layouts.BoxLayout.X_AXIS));
    private com.codename1.ui.Label gui_cclabel = new com.codename1.ui.Label();
    private com.codename1.ui.Container gui_cc = new com.codename1.ui.Container(new com.codename1.ui.layouts.FlowLayout());
    private com.codename1.ui.Container gui_ccdivider = new com.codename1.ui.Container(new com.codename1.ui.layouts.FlowLayout());
    private com.codename1.ui.Container gui_bccwrapper = new com.codename1.ui.Container(new com.codename1.ui.layouts.BoxLayout(com.codename1.ui.layouts.BoxLayout.X_AXIS));
    private com.codename1.ui.Label gui_bcclabel = new com.codename1.ui.Label();
    private com.codename1.ui.Container gui_bcc = new com.codename1.ui.Container(new com.codename1.ui.layouts.FlowLayout());
    private com.codename1.ui.Container gui_bccdivider = new com.codename1.ui.Container(new com.codename1.ui.layouts.FlowLayout());
    private com.codename1.ui.Container gui__26 = new com.codename1.ui.Container(new com.codename1.ui.layouts.BoxLayout(com.codename1.ui.layouts.BoxLayout.X_AXIS));
    private com.codename1.ui.Label gui_subject = new com.codename1.ui.Label();
    private com.codename1.ui.Container gui__27 = new com.codename1.ui.Container(new com.codename1.ui.layouts.FlowLayout());
    private com.codename1.ui.Container gui_attachments = new com.codename1.ui.Container(new com.codename1.ui.layouts.BoxLayout(com.codename1.ui.layouts.BoxLayout.Y_AXIS));
    private com.codename1.ui.Container gui_messagecontent = new com.codename1.ui.Container(new com.codename1.ui.layouts.FlowLayout());
    private com.codename1.ui.Container gui_uppersignature = new com.codename1.ui.Container(new com.codename1.ui.layouts.FlowLayout());
    private com.codename1.ui.Button gui_quotedtextshow = new com.codename1.ui.Button();
    private com.codename1.ui.Container gui_quotedtextbar = new com.codename1.ui.Container(new com.codename1.ui.layouts.BoxLayout(com.codename1.ui.layouts.BoxLayout.Y_AXIS));
    private com.codename1.ui.Container gui_quotedtext = new com.codename1.ui.Container(new com.codename1.ui.layouts.FlowLayout());
    private com.codename1.ui.Container gui_quotedhtml = new com.codename1.ui.Container(new com.codename1.ui.layouts.FlowLayout());
    private com.codename1.ui.Container gui_quotedtextbuttons = new com.codename1.ui.Container(new com.codename1.ui.layouts.BoxLayout(com.codename1.ui.layouts.BoxLayout.X_AXIS));
    private com.codename1.ui.Button gui_quotedtextedit = new com.codename1.ui.Button();
    private com.codename1.ui.Button gui_quotedtextdelete = new com.codename1.ui.Button();
    private com.codename1.ui.Container gui_lowersignature = new com.codename1.ui.Container(new com.codename1.ui.layouts.FlowLayout());


// <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initGuiBuilderComponents(com.codename1.ui.util.Resources resourceObjectInstance) {
        setLayout(new com.codename1.ui.layouts.BoxLayout(com.codename1.ui.layouts.BoxLayout.Y_AXIS));
        setUIID("Container3Android");
        setName("MessageCompose");
        addComponent(gui_);
        gui_.setScrollableY(true);
        gui_.setUIID("Container3Android");
        gui_.setName("");
        gui_.addComponent(gui__1);
        gui__1.setUIID("Container3Android");
        gui__1.setName("_1");
        gui__1.addComponent(gui__2);
        gui__2.setUIID("Container3Android");
        gui__2.setName("_2");
        gui__2.addComponent(gui__3);
        gui__3.setUIID("Container3Android");
        gui__3.setName("_3");
        gui__3.addComponent(gui_fromlabel);
        gui__3.addComponent(gui_identity);
        gui__3.addComponent(gui_pgpinlineindicator);
        gui__3.addComponent(gui_cryptostatus);
        gui_cryptostatus.setUIID("Container3Android");
        gui_cryptostatus.setName("cryptostatus");
        gui_cryptostatus.addComponent(gui__4);
        gui_cryptostatus.addComponent(gui__5);
        gui_cryptostatus.addComponent(gui__6);
        gui__6.setUIID("Container3Android");
        gui__6.setName("_6");
        gui__6.addComponent(com.codename1.ui.layouts.BorderLayout.CENTER, gui_null);
        gui_null.addComponent(gui__7);
        gui_null.addComponent(gui__8);
        gui__7.setUIID("Label10Android");
        gui__7.setName("_7");
        gui__8.setUIID("Label10Android");
        gui__8.setName("_8");
        gui_cryptostatus.addComponent(gui__9);
        gui__9.setUIID("Container3Android");
        gui__9.setName("_9");
        gui__9.addComponent(com.codename1.ui.layouts.BorderLayout.CENTER, gui_null_1);
        gui_null_1.setName("null_1");
        gui_null_1.addComponent(gui__10);
        gui_null_1.addComponent(gui__11);
        gui__10.setUIID("Label10Android");
        gui__10.setName("_10");
        gui__11.setUIID("Label10Android");
        gui__11.setName("_11");
        gui_null_1.setName("null_1");
        gui_cryptostatus.addComponent(gui__12);
        gui__12.setUIID("Container3Android");
        gui__12.setName("_12");
        gui__12.addComponent(com.codename1.ui.layouts.BorderLayout.CENTER, gui_null_2);
        gui_null_2.setName("null_2");
        gui_null_2.addComponent(gui__13);
        gui_null_2.addComponent(gui__14);
        gui_null_2.addComponent(gui__15);
        gui__13.setUIID("Label10Android");
        gui__13.setName("_13");
        gui__14.setUIID("Label10Android");
        gui__14.setName("_14");
        gui__15.setUIID("Label10Android");
        gui__15.setName("_15");
        gui_null_2.setName("null_2");
        gui_cryptostatus.addComponent(gui__16);
        gui__16.setUIID("Container3Android");
        gui__16.setName("_16");
        gui__16.addComponent(com.codename1.ui.layouts.BorderLayout.CENTER, gui_null_3);
        gui_null_3.setName("null_3");
        gui_null_3.addComponent(gui__17);
        gui_null_3.addComponent(gui__18);
        gui__17.setUIID("Label10Android");
        gui__17.setName("_17");
        gui__18.setUIID("Label10Android");
        gui__18.setName("_18");
        gui_null_3.setName("null_3");
        gui_cryptostatus.addComponent(gui__19);
        gui__19.setUIID("Container3Android");
        gui__19.setName("_19");
        gui__19.addComponent(com.codename1.ui.layouts.BorderLayout.CENTER, gui_null_4);
        gui_null_4.setName("null_4");
        gui_null_4.addComponent(gui__20);
        gui_null_4.addComponent(gui__21);
        gui__20.setUIID("Label10Android");
        gui__20.setName("_20");
        gui__21.setUIID("Label10Android");
        gui__21.setName("_21");
        gui_null_4.setName("null_4");
        gui_cryptostatus.addComponent(gui__22);
        gui__4.setUIID("Label10Android");
        gui__4.setName("_4");
        gui__5.setUIID("Label10Android");
        gui__5.setName("_5");
        gui__6.setUIID("Container3Android");
        gui__6.setName("_6");
        gui__9.setUIID("Container3Android");
        gui__9.setName("_9");
        gui__12.setUIID("Container3Android");
        gui__12.setName("_12");
        gui__16.setUIID("Container3Android");
        gui__16.setName("_16");
        gui__19.setUIID("Container3Android");
        gui__19.setName("_19");
        gui__22.setUIID("Label10Android");
        gui__22.setName("_22");
        gui_fromlabel.setText("recipient_from");
        gui_fromlabel.setUIID("AndroidLabel305");
        gui_fromlabel.setName("fromlabel");
        gui_identity.setUIID("Label306Android");
        gui_identity.setName("identity");
        gui_pgpinlineindicator.setUIID("Label10Android");
        gui_pgpinlineindicator.setName("pgpinlineindicator");
        gui_cryptostatus.setUIID("Container3Android");
        gui_cryptostatus.setName("cryptostatus");
        gui__2.addComponent(gui__23);
        gui__2.addComponent(gui_towrapper);
        gui_towrapper.setUIID("Container3Android");
        gui_towrapper.setName("towrapper");
        gui_towrapper.addComponent(gui_tolabel);
        gui_towrapper.addComponent(gui_to);
        gui_towrapper.addComponent(gui_recipientexpandercontainer);
        gui_recipientexpandercontainer.setUIID("Container3Android");
        gui_recipientexpandercontainer.setName("recipientexpandercontainer");
        gui_recipientexpandercontainer.addComponent(com.codename1.ui.layouts.BorderLayout.CENTER, gui_null_5);
        gui_null_5.setName("null_5");
        gui_null_5.addComponent(gui_recipientexpander);
        gui_null_5.addComponent(gui__24);
        gui_recipientexpander.setUIID("Label10Android");
        gui_recipientexpander.setName("recipientexpander");
        gui__24.setUIID("Container3Android");
        gui__24.setName("_24");
        gui_null_5.setName("null_5");
        gui_tolabel.setText("recipient_to");
        gui_tolabel.setUIID("AndroidLabel305");
        gui_tolabel.setName("tolabel");
        gui_to.setUIID("Container331Android");
        gui_to.setName("to");
        gui_recipientexpandercontainer.setUIID("Container3Android");
        gui_recipientexpandercontainer.setName("recipientexpandercontainer");
        gui__2.addComponent(gui__25);
        gui__2.addComponent(gui_ccwrapper);
        gui_ccwrapper.setUIID("Container3Android");
        gui_ccwrapper.setName("ccwrapper");
        gui_ccwrapper.addComponent(gui_cclabel);
        gui_ccwrapper.addComponent(gui_cc);
        gui_cclabel.setText("recipient_cc");
        gui_cclabel.setUIID("AndroidLabel305");
        gui_cclabel.setName("cclabel");
        gui_cc.setUIID("Container331Android");
        gui_cc.setName("cc");
        gui__2.addComponent(gui_ccdivider);
        gui__2.addComponent(gui_bccwrapper);
        gui_bccwrapper.setUIID("Container3Android");
        gui_bccwrapper.setName("bccwrapper");
        gui_bccwrapper.addComponent(gui_bcclabel);
        gui_bccwrapper.addComponent(gui_bcc);
        gui_bcclabel.setText("recipient_bcc");
        gui_bcclabel.setUIID("AndroidLabel305");
        gui_bcclabel.setName("bcclabel");
        gui_bcc.setUIID("Container331Android");
        gui_bcc.setName("bcc");
        gui__2.addComponent(gui_bccdivider);
        gui__3.setUIID("Container3Android");
        gui__3.setName("_3");
        gui__23.setUIID("Container3Android");
        gui__23.setName("_23");
        gui_towrapper.setUIID("Container3Android");
        gui_towrapper.setName("towrapper");
        gui__25.setUIID("Container3Android");
        gui__25.setName("_25");
        gui_ccwrapper.setUIID("Container3Android");
        gui_ccwrapper.setName("ccwrapper");
        gui_ccdivider.setUIID("Container3Android");
        gui_ccdivider.setName("ccdivider");
        gui_bccwrapper.setUIID("Container3Android");
        gui_bccwrapper.setName("bccwrapper");
        gui_bccdivider.setUIID("Container3Android");
        gui_bccdivider.setName("bccdivider");
        gui__1.addComponent(gui__26);
        gui__26.setUIID("Container3Android");
        gui__26.setName("_26");
        gui__26.addComponent(gui_subject);
        gui_subject.setUIID("Label347Android");
        gui_subject.setName("subject");
        gui__1.addComponent(gui__27);
        gui__1.addComponent(gui_attachments);
        gui__1.addComponent(gui_messagecontent);
        gui__1.addComponent(gui_uppersignature);
        gui__1.addComponent(gui_quotedtextshow);
        gui__1.addComponent(gui_quotedtextbar);
        gui_quotedtextbar.setUIID("Container3Android");
        gui_quotedtextbar.setName("quotedtextbar");
        gui_quotedtextbar.addComponent(gui_quotedtext);
        gui_quotedtextbar.addComponent(gui_quotedhtml);
        gui_quotedtextbar.addComponent(gui_quotedtextbuttons);
        gui_quotedtextbuttons.setUIID("Container3Android");
        gui_quotedtextbuttons.setName("quotedtextbuttons");
        gui_quotedtextbuttons.addComponent(gui_quotedtextedit);
        gui_quotedtextbuttons.addComponent(gui_quotedtextdelete);
        gui_quotedtextedit.setUIID("Button356Android");
        gui_quotedtextedit.setName("quotedtextedit");
        gui_quotedtextdelete.setUIID("Button357Android");
        gui_quotedtextdelete.setName("quotedtextdelete");
        gui_quotedtext.setUIID("Container3Android");
        gui_quotedtext.setName("quotedtext");
        gui_quotedhtml.setUIID("Container3Android");
        gui_quotedhtml.setName("quotedhtml");
        gui_quotedtextbuttons.setUIID("Container3Android");
        gui_quotedtextbuttons.setName("quotedtextbuttons");
        gui__1.addComponent(gui_lowersignature);
        gui__2.setUIID("Container3Android");
        gui__2.setName("_2");
        gui__26.setUIID("Container3Android");
        gui__26.setName("_26");
        gui__27.setUIID("Container3Android");
        gui__27.setName("_27");
        gui_attachments.setUIID("Container3Android");
        gui_attachments.setName("attachments");
        gui_messagecontent.setUIID("Container3Android");
        gui_messagecontent.setName("messagecontent");
        gui_uppersignature.setUIID("Container3Android");
        gui_uppersignature.setName("uppersignature");
        gui_quotedtextshow.setText("message_compose_show_quoted_text_action");
        gui_quotedtextshow.setUIID("Button20Android");
        gui_quotedtextshow.setName("quotedtextshow");
        gui_quotedtextbar.setUIID("Container3Android");
        gui_quotedtextbar.setName("quotedtextbar");
        gui_lowersignature.setUIID("Container3Android");
        gui_lowersignature.setName("lowersignature");
        gui__1.setUIID("Container3Android");
        gui__1.setName("_1");
        gui_.setScrollableY(true);
        gui_.setUIID("Container3Android");
        gui_.setName("");
    }// </editor-fold>

//-- DON'T EDIT ABOVE THIS LINE!!!
}
